import pandas as pd
df = pd.read_csv('Electric_Vehicle_Population_Data.csv')
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())
print(df['Model'])
print(df['City'])
df = pd.read_csv('Electric_Vehicle_Population_Data.csv')
print(df.columns)
print(df.columns.tolist())
print("Информация о данных:")
print(df.info())
print("\nСтатистическое описание данных:")
print(df.describe())